### PR TITLE
Implemented Affecto.Logging.NLog library

### PR DESCRIPTION
**Pull request by gregorypilipenko**
Hi. In our project we had to adopt functionality used Affecto.Logging together with Affecto.Logging.Log4Net (made by another team) to our part of code, which already used NLog for logging. Currently we use a workaround. And it could be nice to have a NuGet package similar to Affecto.Logging.Log4Net, but made for NLog.
In my fork I have implemented Affecto.Logging.NLog library in the same manner as Affecto.Logging.Log4Net.
Please, let me know it it is good enough to be merged in your repository and published as a NuGet packege.
Thanks.

### CODE REVIEW

**Comment by johannesvaltonen** [comment]
Hi. Thanks for the PR @gregorypilipenko. This has been on our to-do list for a while, so it's nice to get help.

I reviewed your code. The only thing I would like you to change is the naming convention of instance variables. We use standard .NET naming convention, so the instance variables should not begin with an underscore. Otherwise it looks good!

**Comment by gregorypilipenko** [comment]
Hi.
Underscores was suggested by ReSharper. But I have removed them, as you requested.

**Comment by gregorypilipenko** [comment]
Hi Johannes,
Thanks for merging my pull request. Will you publish my library as nuget package (there is .nuspec file already included in the project). Or I need to do something by myself, to have Affecto.Logging.NLog package available from nuget.org?

Thanks

**Comment by johannesvaltonen** [comment]
Hi,

I just completed the release. The NuGet package is available after indexing in https://www.nuget.org/packages/Affecto.Logging.NLog

Thanks

**Comment by gregorypilipenko** [comment]
That is great!

Thanks a lot!

2017-01-09 10:42 GMT+02:00 Johannes Valtonen <notifications@github.com>:

**Pull request merged**
